### ISSUE TITLE
Main_equilibrium_D_Bar

### ISSUE THREAD

**Issue by vaishnavtv** [ramaniitrgoyal92/Tensegrity_Engineering_Analysis_Master-TEAM-#2]
I ran this file under 
>../Software_Verification_and_Examples/Statics_Examples/00_Software_Verification_D_bar_Statics'

- It seems as if you're printing a number of optimization results in the command window including:
Force_den and options (presumably for optimization). This isn't necessary, is it?
Saving the data at the end is also printing this warning:

> Warning: Figure is saved in D_Bar_Statics.mat. Saving
graphics handle variables can cause the creation of very
large files. To save graphics figures, use savefig. 
> In Main_equilibrium_D_Bar (line 68) 

- Also, the tenseg_plot_physical plot at the end is a little messy at the moment. 
![DbarStatics00](https://user-images.githubusercontent.com/8902316/63231046-664f9180-c1db-11e9-8408-7c8f30e04b39.jpg)

- In the user manual, it is written that running the file yields the optimization results in the command window. The program isn't displaying the names of the optimized variables though: 

>  ans =
> 
>     12     6
> 
>  ans =
> 
>      5
> 
> 
> ans =
> 
>      5

**Comment by ramaniitrgoyal92** [comment]
Yes, you are right! We updated the software according to your suggestions. Thanks a lot!

**Comment by vaishnavtv** [comment]
Getting this error when I run this file:

> Undefined function or variable 'tenseg_plot_physical'.

> Error in Main_equilibrium_D_Bar (line 66)
> tenseg_plot_physical(N,C_b,C_s,[],[],[],[],'Sradius',LABEL,BarWidth,StringWidth);

**Comment by vaishnavtv** [comment]
Getting the same error when I run the TBar and prism examples too. Not for Kite though. 
But I don't see any output when I run Kite, am I not supposed to see the results of the statics analysis in the command window? Masses of the bars, strings, and the minimum mass?

**Comment by ramaniitrgoyal92** [comment]
Function tenseg_plot_physical.m is added to Function_Library.
All the results are shown in MATLAB workspace, see N, C_s, C_b, W, Mass_bar, Mass_string, MIN_MASS (structure total mass). These are what we interested in tensegrity statics analysis. Thanks!

**Comment by ramaniitrgoyal92** [comment]
For the Kite problem, I also added:
kite.bar_material='Aluminum'; % Specify bar material Aluminum, UHMWPE or Steel
kite.string_material='Aluminum'; % Specify bar material Aluminum, UHMWPE or Steel
kite.bar_failure='yielding_n_buckling'; % gives maximum mass subject to yielding and buckling
% Solve for an equilibrium condition 
[Force_den,Support_Load,LABEL,MIN_MASS,Mass_bar,Mass_string,BarWidth_in,StringWidth_in,Loop] = tenseg_equilibrium_minimal_mass(kite);
Now, you can see all the results.

**Comment by vaishnavtv** [comment]
I see that tenseg_plot_physical is added, but the plots are still messy, as I remarked when I opened the issue. Any chance you could fix this? I understand it's a cosmetic change, so I don't have a problem with it in its current state, but it would still be a useful improvement should you be able to do it.

**Comment by ramaniitrgoyal92** [comment]
Thanks for pointing out this issue! We can do it for this example, but it would still have the same issue when plotting structures with high complexity. It is hard to get a uniform and automated plot adjustment since the plot is determined by the plot size and topology. We would suggest user to manually move the labels to get more pretty figures.

**Comment by vaishnavtv** [comment]
I understand. Closing this issue.
