### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by vaishnavtv** [ramaniitrgoyal92/Tensegrity_Engineering_Analysis_Master-TEAM-#3]
To solve the linear programming problem for an equilibrium solution, the software is calling the 'linprog' function, a part of the Optimization toolbox in MATLAB. The User Manual needs to specify this requirement either in the 'System Overview' section, or in the software Readme itself.

**Comment by ramaniitrgoyal92** [comment]
We updated our user manual. Thanks a lot!

**Comment by vaishnavtv** [comment]
Please amend your README to reflect the dependencies required as well.

**Comment by ramaniitrgoyal92** [comment]
Thanks for reminding! We have added the system requirement of installing this software in the README.

**Comment by ramaniitrgoyal92** [comment]
We added:
Undergraduate linear algebra and some basic knowledge of MATLAB is required to understand the codes well. This software is developed based on:

• 64-bit Windows • MATLAB • MATLAB Optimization Toolbox Note: Win7/Win10/Mac OS/Linux/Win XP/Win Vista compatible with a MATLAB version later than 2009a should work fine. However, we encourage the user to run the software with the latest MATLAB release if possible.

**Comment by vaishnavtv** [comment]
Understood. Closing the issue.
