### ISSUE TITLE
Double Pendulum Dynamics

### ISSUE THREAD

**Issue by vaishnavtv** [ramaniitrgoyal92/Tensegrity_Engineering_Analysis_Master-TEAM-#4]
File in: ../Software_Verification_and_Examples/Dynamics_Examples/00_Software_Verification_Double_Pendulum/MOTES_Solution

- At multiple points during the simulation, I'm receiving a warning in the command window:
>  Warning: Matrix is close to singular or badly scaled.
> Results may be inaccurate. RCOND =  1.863212e-16. 
> > In bar_length_correction_ClassK (line 37)
>   In tenseg_dyn_ckopen_fnc (line 106)
>   In ode4Ck (line 79)
>   In tenseg_sim_classkopen (line 84)
>   In Main_Double_Pendulum_Dynamics_MOTES (line 90)

- This file also seems to be printing the time at every step. I don't believe this is necessary, and only serves to hinder computational performance. 

- This is trivial, but it might be more useful to plot the node history of your structure before the animation begins.

**Comment by ramaniitrgoyal92** [comment]
Thanks for pointing out! We did the suggested changes. Thanks a lot!

**Comment by vaishnavtv** [comment]
Getting this error now:

> > Error using ode4Ck (line 43)
> Unable to evaluate the ODEFUN at t0,y0. Undefined function 'v' for
> input arguments of type 'double'.
> 
> Error in tenseg_sim_classkopen (line 83)
> Xhist = ode4Ck(@tenseg_dyn_ckopen_fnc,t,X0,INPUTS);
> 
> Error in Main_Double_Pendulum_Dynamics_MOTES (line 90)
> [History,debug] = tenseg_sim_classkopen(classK_test);
>  

Same for:
- Main_Example_class_k_Dbar_Dynamics  
- Main_Example_class_k_Dbar_Constraint_Dynamics  
- Main_Example_class_k_Pend  
and I suppose the rest of the dynamics examples as well.

**Comment by ramaniitrgoyal92** [comment]
Thanks! It was because we did some changes to function skew.m, the problem has been solved. Sorry for the inconvenience, please check the code again. Thank you!

**Comment by vaishnavtv** [comment]
The files are working now, great! I'll close the issue.
