### ISSUE TITLE
Dangling references to old name

### ISSUE THREAD

**Issue by apsabelhaus** [ramaniitrgoyal92/Tensegrity_Engineering_Analysis_Master-TEAM-#5]
There are a few places where the documentation still says "TEAM" - for example, in the readme. It would be good to do a full review of everywhere the name is used, and update to MOTES. Do a search through all text files.

**Comment by apsabelhaus** [comment]
I'll also add here that there are some typos that the authors may want to fix. Lots of "Structrues" not "Structures."

**Comment by ramaniitrgoyal92** [comment]
We have updated all the documents correcting typos and Name. Thanks!

**Comment by apsabelhaus** [comment]
Looks fine to me!
