### ISSUE TITLE
Verifying that the authors wrote all included functions

### ISSUE THREAD

**Issue by apsabelhaus** [ramaniitrgoyal92/Tensegrity_Engineering_Analysis_Master-TEAM-#6]
Some of the functions strike me as very different in documentation and tone, to the extent that I'd like to confirm their origin and authorship. Specifically, 

Function_Library/ode4.m

seems to actually be from the following repository:

https://github.com/kakearney/ecosystem-pkg/blob/master/odefixed/ode4.m

...which to my knowledge is not written by the authors. Can you confirm this is your code?

**Comment by vaishnavtv** [comment]
@ramaniitrgoyal92, in light of what @apsabelhaus pointed out, the line in the paper "The software runs a **self-developed** modified Runge-Kutta integration package to solve the nonlinear differential equations." might need to be amended.

**Comment by ramaniitrgoyal92** [comment]
Thanks for letting us know! We apologize for this critical issue. ode4.m is not developed by us, and ode4C1.m, ode4CK.m are developed based on ode4.m. Copyright of the developers has been added to these functions. 
Thanks indeed!

> Some of the functions strike me as very different in documentation and tone, to the extent that I'd like to confirm their origin and authorship. Specifically,
> 
> Function_Library/ode4.m
> 
> seems to actually be from the following repository:
> 
> https://github.com/kakearney/ecosystem-pkg/blob/master/odefixed/ode4.m
> 
> ...which to my knowledge is not written by the authors. Can you confirm this is your code?

**Comment by ramaniitrgoyal92** [comment]
> @ramaniitrgoyal92, in light of what @apsabelhaus pointed out, the line in the paper "The software runs a **self-developed** modified Runge-Kutta integration package to solve the nonlinear differential equations." might need to be amended.

We have changed the sentence to read: "The software runs a modified Runge-Kutta integration package to solve the nonlinear differential equations."
Thanks!

**Comment by apsabelhaus** [comment]
@Kevin-Mattheus-Moerman could we get a quick decision here on JOSS' policies as relate to copy-pasting other people's code in a JOSS submission? Here's my understanding of the current situation and it would be helpful if the editor could direct the authors on what to do next.

The authors have copied the file ode4.m (among some others) from the repository kakearney/ecosystem-pkg, as in

https://github.com/kakearney/ecosystem-pkg/blob/master/odefixed/ode4.m

and placed the line 

"This function is written by Kelly Kearney: https://github.com/kakearney/ecosystem-pkg/blob/master/odefixed/ode4.m."

at the top of the copied file into their MOTES repository. 

@ramaniitrgoyal92 , stating attribution of a file is *not* the same as including the copyright from that file. Specifically, the repository you copied from has the MIT license: https://github.com/kakearney/ecosystem-pkg/blob/master/LICENSE.txt, which says "The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software." That MIT license is not currently included in your repository nor is it explained how that license relates to your own original work and your Mozilla license.

I don't know what to do about this, but I do believe that MOTES is currently in violation of the other code's license, as well as potentially JOSS' rules if the code is supposed to be all original work. For example - I would think if the authors copied text from a traditional journal paper, and submitted it as their own somewhere else, this would be academic dishonesty and grounds for rejection. The authors may be unfamiliar with open source licensing, since the responses in this thread have been inexact (stating attribution but not licensing, for example.) It would be helpful for the authors to figure this out and provide a thorough solution then let us know when it's fixed, or please let me know if I'm misunderstanding something.

**Comment by ramaniitrgoyal92** [comment]
@apsabelhaus @Kevin-Mattheus-Moerman, 
Sorry for our unfamiliarity with the open-source licensing. We didn't mean to use somebody's code without giving them due credit. We thought it is sufficient to mention that it was written by 'Kelly Kearney'. The integration scheme used in function 'ode4.m' is a commonly used modified integration scheme. We can write our own integration function to replace this function from the repository if you think that is the best way to go forward. 
**We also have added the MIT copyright notice and permission notice in the function 'ode4.m' and two functions that are built on that.** 

We are again sorry for not being careful enough about this from the start. Please advice us on this critical issue. We can write our own function as well if you advice for that.
