### ISSUE TITLE
Contributing missing

### ISSUE THREAD

**Issue by apsabelhaus** [ramaniitrgoyal92/Tensegrity_Engineering_Analysis_Master-TEAM-#7]
JOSS requires for community guidelines:

Are there clear guidelines for third parties wishing to 1) Contribute to the software

...which is currently not present. Contact info is great, but add at least a sentence about contributing so I can check the box.

**Comment by ramaniitrgoyal92** [comment]
> JOSS requires for community guidelines:
> 
> Are there clear guidelines for third parties wishing to 1) Contribute to the software
> 
> ...which is currently not present. Contact info is great, but add at least a sentence about contributing so I can check the box.

Thanks for pointing out. We updated our README.md to add contributing guidelines to the added section “Join MOTES Community and Contribute”.
Thanks!

**Comment by ramaniitrgoyal92** [comment]
### Join MOTES Community and Contribute

#### How to contribute

Feedbacks and contributions are appreciated. Please use the same nomenclature so that everybody could be on the same page.

1. Fork it
2. Submit a pull request OR send emails to help desk.

We will reply to you ASAP.

#### Coding standards

* MATLAB (>= 2009a)
* Function input and output comments
* Use the same Nomenclature as follows

#### Nomenclature

##### Geometry: 
    N: initial node positions
    C_b: bar connectivity
    C_s: string connectivity
    C_r: Bar center of mass 'connectivity'
    C_sb: string connections to bars
    C_ss: string connections to string nodes
    C_bb: non-zero columns of C_b (old C_b matrix)
    C_nb: satisfies R_b = N*C_nb^T*C_r'
    B: bar matrix
    S: string matrix
    s_0: resting string lengths
    n: number of nodes
    beta: number of bars
    alpha: number of string members
    sigma: number of string point mass nodes
##### Force
    gamma: string member force densities
    lambda: bar member force densities 
    P: constraint matrix
    D: constraint matrix
    M: mass matrix used in dynamics
    Minv: inverse of M
    W: external node forces
    k: string stiffness coefficients
    constants: various constants throughout the simulation
##### Initial Conditions
	Nd0: initial node velocities
    m: bar masses
    ms: string node point masses
    mgyro: gyro wheel masses
    gyro_r: gyro wheel radii
    gyro_h: gyro wheel heights
    gyro_omega: gyro angular rates
    Jt_hat: transaxial bar+gyro moments of inertia
    Ja_hat: axial bar+gyro moments of inertia
    len_hat: initial bar lengths
##### Simulation
    tf: simulation time duration
    dt: simulation time step
    W: external node forces
    k: string stiffness coefficients
    N0: initial node positions
    Nd0: initial node velocities
    sim: integration specification variables

**Comment by apsabelhaus** [comment]
done.
