### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by apsabelhaus** [ramaniitrgoyal92/Tensegrity_Engineering_Analysis_Master-TEAM-#8]
Though the API documentation is probably acceptable for JOSS' minimum standards, I would recommend (if the authors want the software to be more useful) to standardize the way that files are documented, since the descriptions and level of detail vary among files.

It's also really helpful for MATLAB's built-in 'help' functionality to work with your files. To do so, the comments need to be unbroken at the top of functions: 'help' only echoes back the first block of comments. You can add some % in the empty lines to fix this.

**Comment by ramaniitrgoyal92** [comment]
Thanks for pointing out. We updated the help format to MATLAB's built-in 'help' functionality. In addition, we give a README.md for each folder to clarify what does the folder have, problem statement, and what should be the expected results. 
Thanks!

**Comment by apsabelhaus** [comment]
looks fine. I would suggest that someone do a proofread of the added README files, some are still unclear and may be translation issues for English as a second language: example, README in Function_Library says "file" where you really mean "folder." I'll close the issue since this looks close enough to me!
