### ISSUE TITLE
JOSS paper

### ISSUE THREAD

**Issue by vaishnavtv** [ramaniitrgoyal92/Tensegrity_Engineering_Analysis_Master-TEAM-#9]
In the JOSS paper, it would be helpful to address how the software is different from [stedy](https://github.com/isrlab/stedy) given how similar the two softwares are in concept and application. From what I understand, the fundamental differences between stedy and MOTES include:

- Difference in Formulation of the dynamics equations.
- Statics present in MOTES
- Difference in the choice of integration solver used and the analytical method of correction
- Strings with masses.

**Comment by ramaniitrgoyal92** [comment]
We have updated the paper to include:

STEDY [@Stedy_2019], a similar tensegrity simulator, uses a different correction step and formulation to run the dynamics. The added advantage with MOTES is the ability to model massive strings and to design minimum mass structures using static analysis.

**Comment by vaishnavtv** [comment]
Alright, thank you.
